Update instructions for releasing supergraph component (#126)
* Update instructions for releasing supergraph component

1. Use `--debug` in `cargo xtask dist` so `Cargo.lock` can be updated. Without that param, you'll get the following error of sadness:
    ```
    ➜ cargo xtask dist
        Finished dev [unoptimized + debuginfo] target(s) in 0.04s
        Running `target/debug/xtask dist`
    info: running `cargo build --release --locked --target x86_64-apple-darwin` in `/Users/weatherman/code/apollographql/federation-rs/federation-1`
    info: running `cargo build --release --locked --target x86_64-apple-darwin` in `/Users/weatherman/code/apollographql/federation-rs/federation-2`
    info: running `cargo build --release --locked --target x86_64-apple-darwin` in `/Users/weatherman/code/apollographql/federation-rs/federation-2/router-bridge`
    error: the lock file /Users/weatherman/code/apollographql/federation-rs/federation-2/Cargo.lock needs to be updated but --locked was passed to prevent this
    If you want to try to generate the lock file without accessing the network, remove the --locked flag and use --offline instead.

    Error: Could not run command in `/Users/weatherman/code/apollographql/federation-rs/federation-2/router-bridge`

    Caused by:
        0: Encountered an issue while executing `cargo build --release --locked --target x86_64-apple-darwin`
        1: Exited with status code 101
    ```
1. Add instructions for tagging `latest-2` release so the supergraph component is downloaded by rover