Add .tool-versions file for asdf
When `npm` in `$PATH` is the shim from asdf, compiling might fail with an
error like this:

```
  --- stderr
  No version is set for command npm
  Consider adding one of the following versions in your config file at
  nodejs 16.9.1
  thread 'main' panicked at 'assertion failed:
Command::new(&npm).current_dir(&current_dir).args(&[\"install\"]).status().unwrap().success()',
/Users/simon/.cargo/git/checkouts/federation-rs-edb4f8c0f5624a5c/33659ef/federation-2/router-bridge/build.rs:29:9
```

This PR copies `.tool-versions` from the router repository, which tells asdf
which version to use.